### ISSUE TITLE
Cant work with Workload Identity 

### ISSUE THREAD

**Issue by hsenol1** [fjogeleit/policy-reporter#431]
To use GCS as our storage and push our reports to there, I need to provide JSON for target.gcs.credentials, however this is not the way Workload Identity works actually. In pkg-helper-gcp.go file, 

`// NewGCSClient creates a new GCS.client to send Results to GCS Bucket
func NewGCSClient(ctx context.Context, credentials, bucket string) GCPClient {
	cred, err := google.CredentialsFromJSON(ctx, []byte(credentials), storage.ScopeReadWrite)
	if err != nil {
		zap.L().Error("error while creating GCS credentials", zap.Error(err))
		return nil
	}

	client, err := storage.NewClient(ctx, option.WithCredentials(cred))
	if err != nil {
		zap.L().Error("error while creating GCS client", zap.Error(err))
		return nil
	}

	return &gcsClient{
		bucket,
		client,
	}
}`

Above function forces users to provide JSON credentials, otherwise logs are **error	GoogleCloudStorage.Credentials has not been declared**

**Comment by fjogeleit** [comment]
I’ll take a look on it

**Comment by hsenol1** [comment]
> I’ll take a look on it

In addition, I tried passing` target.gcp.credentials: "" and target.gcp.secretRef: "secretName" `
but still, have the same log output.

**Comment by fjogeleit** [comment]
I merged a fix for it, I try to release it at the end of the week. Do you want a test build you can try?

**Comment by hsenol1** [comment]
Definitely, if you can provide a new image and tag, I'd like to try it. Thanks for such a quick solution.

**Comment by hsenol1** [comment]
So how can I access the test build? I checked the CI pipeline but couldn't figure it out.

**Comment by fjogeleit** [comment]
I created a tag [2.19.0-RC1](https://github.com/kyverno/policy-reporter/tree/v2.19.0-RC1) which you can test. Just overwrite the `image.tag` value with `2.19.0-RC1`.

**Comment by hsenol1** [comment]
Tested it, still having the same error. 

`              gcs:
                enabled: true
                # GCS (Google Cloud Storage) Service Accout Credentials
                credentials: "{}"
                # receive the credentials from an existing secret instead
                secretRef: ""
                # Mounted secret path by Secrets Controller, secret should be in json format
                mountedSecret: ""
                # GCS Bucket
                bucket: "trivy-docs"
                # minimum priority "" < info < warning < critical < error
                minimumPriority: ""
                # list of sources which should send to GCS
                sources: []
                # Skip already existing PolicyReportResults on startup
                skipExistingOnStartup: true
                # Added as additional properties to each gcs event
                customFields: {}
                # filter results send by namespaces, policies and priorities
                filter: {}
                # add additional s3 channels with different configurations and filters
                channels: []`

is the configuration I use. The error log is same as in the first post in this issue.

**Comment by fjogeleit** [comment]
`credentials` needs to be an empty string, not an empty object string.

**Comment by hsenol1** [comment]
Also tried that, credentials: "" gives the same error.

**Comment by fjogeleit** [comment]
which error? `error while creating GCS credentials` ?

**Comment by hsenol1** [comment]
In the pod logs, you see it as "1.7151700083750553e+09	error	GoogleCloudStorage.Credentials has not been declared"

**Comment by fjogeleit** [comment]
okay, will fix it and prepare another build

**Comment by fjogeleit** [comment]
You can test tag `2.19.0-RC2`

**Comment by hsenol1** [comment]
It says "GoogleCloudStorage configured" now :) Thank you. But I wonder, since there is no information on docs, what is the time interval for that? I mean, it writes to GCP Buckets for every 5 mins, 1 hour or so... 

Again, thanks for quick build and solution.

**Comment by fjogeleit** [comment]
there is no interval, it writes each event for new results as soon as a new result was detected
